version: '3.8'
services:
  bot:
    build: .
    env_file: .env
    volumes:
      - ./users.db:/app/users.db
    restart: unless-stopped
  api:
    build: .
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./users.db:/app/users.db
    restart: unless-stopped
